name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Bun
      run: curl -fsSL https://bun.sh/install | bash
      
    - name: Set up Bun environment
      run: |
        echo "BUN_INSTALL=\"$HOME/.bun\"" >> $GITHUB_ENV
        echo "PATH=\"$BUN_INSTALL/bin:$PATH\"" >> $GITHUB_ENV
      shell: bash

    - name: Install Dependencies
      run: bun i

    - name: Run eslint
      run: bun run eslint

    - name: Run prettier
      run: bun run style-check

    - name: Run build
      run: bun run build

    - name: Run unit tests
      run: bun run test
